### ISSUE TITLE
[Question] need to multiply by 8 to assign a value to pCfgEntry? 

### ISSUE THREAD

**Issue by 827Dream** [jdu2600/CFG-FindHiddenShellcode#1]
When I checked the disassembly of LdrpDispatchUserCallTarget and saw whether the verification address is valid, it was through bitmapbase+(target >> 0x9)*8, so I am not sure whether it needs to be multiplied by 8 when assigning pCfgEntry

mov     r11, cs:qword_1801813A8
mov     r10, rax
shr     r10, 9
mov     r11, [r11+r10*8]

https://github.com/jdu2600/CFG-FindHiddenShellcode/blob/d1b2638721f4ad0f156cadf7d976d9cf8c0105fd/main.cpp#L38

**Comment by jdu2600** [comment]
Pointer arithmetic works in multiples of pointer size.  This is so that `p++` returns the next pointer,  and `p + index` is equivalent to `p[index]`. (If you want to do numerical arithmetic you need to cast to numerical type such as `ULONG_PTR` first).

In this case, `pCfgBitMap` is a `PULONG_PTR` and `sizeof(PULONG_PTR)` is 8 on x64. So adding the index to the pointer actually increases the value of the pointer by `8 * index`.  The disassembly should be similar to what you've shown.

**Comment by 827Dream** [comment]
Thanks for the reply, I was trying to write the same code myself, I was too careless to look at the code carefully LOL
